title: Selamat Datang Di Blog
email: maulanasaputra11091082@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: maulana20
github_username:  maulana20

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Paginate
paginate: 1
paginate_path: "/page/:num/"
