title: Maulana Saputra Blog's
author:
  name: Maulana Saputra
  email: maulanasaputra11091082@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  maulana20
linkedin_username: maulana-saputra-a58711b7

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Paginate
paginate: 10
paginate_path: "/page/:num/"
